### ISSUE TITLE
Running bin2h on Mac OS X

### ISSUE THREAD

**Issue by Kladdy** [rinthel/bin2h#1]
Great tool, very compact and the source looks great and readably. However, Im having trouble getting it to run on Mac. There are a few dependencies which I am unsure how to actually use, how would one install the required dependencies from the Dependency.cmake file? Would it be possible for you to release a compiled binary, if you have access to a Mac? Sorry for my dumbness.

**Comment by Kladdy** [comment]
Got it to work, thanks!

**Comment by rinthel** [comment]
thanks for your comment! actually, I wrote this tool for personal use, so the documentation about the installation, build and usage is poor now. I’ll add some explanation about them.

**Comment by rinthel** [comment]
541266926c03b8594beca9e21198e98f51a34094
