### ISSUE TITLE
Dot '.' characters resulting in output symbols

### ISSUE THREAD

**Issue by adimeco** [rinthel/bin2h#2]
When converting an input file containing several dots in its name (ie: "my.file.bin"), the resulting  symbol actually contains a dot. For the given example the output would be:

static const unsigned long MY.FILE_SIZE = 963;
static const unsigned char MY.FILE[MY.FILE_SIZE] = {
// ...
}

The expected output is:

static const unsigned long MY_FILE_SIZE = 963;
static const unsigned char MY_FILE[MY_FILE_SIZE] = {
// ...
}

**Comment by rinthel** [comment]
Thanks for reporting! Solved by 52a01778013e29e251fdba67af227b9b40b471e8
